name: Copy File to All Repos

on:
 issues:
  type:
   -closed
   -opened

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Authenticate with GitHub
        run: |
          echo ${{ secrets.PYTHON_SECRET }} | gh auth login --with-token

      - name: Checkout Source Repository
        uses: actions/checkout@v2

      - name: Copy File to All Repos
        run: |
          FILE_PATH="sonar.properties"
          FILE_CONTENT="$(cat $FILE_PATH | base64)"

          ORG_NAME="Prasanna-source31"
          SOURCE_REPO="XXX"
          TARGET_REPOS=$(gh repo list $ORG_NAME --json=name --jq=".[] | select(.name!=\"$SOURCE_REPO\") | .name")

          for REPO in $TARGET_REPOS; do
            curl -X PUT \
              -H "Authorization: Bearer $TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              -d "{\"path\":\"$FILE_PATH\",\"message\":\"Copy $FILE_PATH\",\"content\":\"$FILE_CONTENT\"}" \
              "https://api.github.com/repos/$ORG_NAME/$REPO/contents/$FILE_PATH"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.PYTHON_SECRET }}
