name: Copy File to All Repos

on:
 issues:
  type:
   -closed
   -opened

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Authenticate with GitHub
        run: |
          echo ${{ secrets.PYTHON_SECRET }} | gh auth login --with-token

      - name: Checkout Source Repository
        uses: actions/checkout@v2

      - name: Copy File to All Repos
        run: |
          FILE_PATH="sonar.properties"
          FILE_CONTENT="$(cat $FILE_PATH | base64)"

          ORG_NAME="Prasanna-source31"
          SOURCE_REPO="XXX"
          TARGET_REPOS=$(gh repo list $ORG_NAME --json=name --jq=".[] | select(.name!=\"$SOURCE_REPO\") | .name")

          for REPO in $TARGET_REPOS; do
            curl -X PUT \
              -H "Authorization: Bearer $TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              -d "{\"path\":\"$FILE_PATH\",\"message\":\"Copy $FILE_PATH\",\"content\":\"$FILE_CONTENT\"}" \
              "https://api.github.com/repos/$ORG_NAME/$REPO/contents/$FILE_PATH"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.PYTHON_SECRET }}
- name: Send Teams Notification
  if: ${{ always() }}
  env:
    TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
  run: |
    if [[ "${{ job.status }}" == "success" ]]; then
      status_text="succeeded"
      status_color="#36a64f"
    fi

    if [[ "${{ job.status }}" == "failure" ]]; then
      status_text="failed"
      status_color="#d9534f"
    fi

    project_key="${{ steps.get_project_key.outputs.project_key }}"
    report_url="http://20.113.139.49:9000/dashboard?id=$project_key"
    echo "Report URL: $report_url"
    workflow_file_name="${GITHUB_WORKFLOW}"
    workflow_file_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}?check_suite_focus=true"
    payload="{
      \"@type\": \"MessageCard\",
      \"themeColor\": \"${status_color}\",
      \"title\": \"GitHub Actions Workflow\",
      \"text\": \"Workflow has ${status_text}: ${{ github.repository }}\",
      \"sections\": [
        {
          \"activityTitle\": \"SonarQube Analysis\",
          \"activitySubtitle\": \"${status_text}\",
          \"activityImage\": \"https://www.sonarqube.org/logos/index/favicon.png\",
          \"facts\": [
            {
              \"name\": \"Repository\",
              \"value\": \"${{ github.repository }}\"
            },
            {
              \"name\": \"Report\",
              \"value\": \"[SonarQube Analysis Report](${report_url})\"
            },
            {
              \"name\": \"Workflow File\",
              \"value\": \"[${workflow_file_name}](${workflow_file_url})\"
            }
          ]
        }
      ]
    }"

    curl -X POST -H "Content-Type: application/json" -d "$payload" $TEAMS_WEBHOOK_URL
